In [2]:
!pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

Looking in indexes: https://download.pytorch.org/whl/cu126



[notice] A new release of pip is available: 23.2.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
print(torch.__version__)

2.6.0+cu126


# Tensors in PyTorch


## Types of Tensors


### Scalars
It is Used to create 1D array or 0th dimension tensor

In [5]:
scalar=torch.tensor(7)
scalar.ndim,scalar.shape

(0, torch.Size([]))

### Vector
Vectors are 2d array having 1 dimension


In [6]:
vector=torch.tensor([1,2,3,4,5])
vector.shape,vector.ndim

(torch.Size([1, 5]), 2)

### Matrix
Matrix are 2d arrays and have dimension of 2


In [7]:
MATRIX=torch.tensor([[1,2,3,4,5]])
MATRIX.shape,MATRIX.ndim

(torch.Size([1, 5]), 2)

### Tensors
It is 3-d and have 3 brackets


In [8]:
TENSOR=torch.tensor([[[1,2,3,4,5]],[[6,7,8,9,10]]])
TENSOR.shape,TENSOR.ndim

(torch.Size([2, 1, 5]), 3)

## Creating and using Random Tensors

We can create Random tensor with the help cmd `torch.rand()`
<br> In this we use input parameters like m,n for shape of tensor


In [9]:
random_tensor=torch.rand(size=(3,4))
random_tensor

tensor([[0.8188, 0.4593, 0.6171, 0.7699],
        [0.4196, 0.9346, 0.7815, 0.4236],
        [0.2532, 0.6381, 0.6068, 0.5587]])

In [10]:
random_tensor.shape,random_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

We can create matrix with all zero using `torch.zeros(size=(x,y))` function and same goes for ones `torch.ones(size(x,y))`


In [11]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Range in tensors

`torch.range(0,10)` || `torch.arange(1,10)`
<br>
step=used to add (+steps)



In [12]:
one_to_tens=torch.arange(0,11,step=2)
one_to_tens

tensor([ 0,  2,  4,  6,  8, 10])

### creating a tensor of same shape

In [13]:
one_to_tens_ones=torch.ones_like(input=one_to_tens)
one_to_tens_ones

tensor([1, 1, 1, 1, 1, 1])

### Tensor Dtypes


Precision is used for details in
<br>
**Note** It gives us 3 Errors
1. Tensor not right Dtype
2. Tensor not in correct shape
3. Tensor on not on right Device

| Datatype | Symbol  | Role                  |
|----------|---------|-----------------------|
| float32  | none    | used for float 32 bit |
| float16  | float16 |                       |
|

In [14]:
float_32_tensor=torch.tensor([[[1,2,3,4,5]],[[6,7,8,9,10]]],
                             dtype=None,
                             device="cuda")

float_32_tensor

tensor([[[ 1,  2,  3,  4,  5]],

        [[ 6,  7,  8,  9, 10]]], device='cuda:0')

In [15]:
#Solving not right Datatype tensor
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([[[ 1.,  2.,  3.,  4.,  5.]],

        [[ 6.,  7.,  8.,  9., 10.]]], device='cuda:0', dtype=torch.float16)

## Getting information from tensor and manipulating tensors

### Extracting information:
1. to get datatype we can use `tensor.dtype`
2. to get shape we can use `tensor.shape`
3. to get right device `tensor.device`

In [16]:
print(f"datatype of random tensor : {random_tensor.dtype}")
print(f"shape of random tensor : {random_tensor.shape}")
print(f"device of random tensor : {random_tensor.device}")

datatype of random tensor : torch.float32
shape of random tensor : torch.Size([3, 4])
device of random tensor : cpu


### Manipulating tensors

**Operations**
1. Addition
2. Subtraction
3. Multiplication
4. Division
5. Matrix Multiplication

In [17]:
#creating the tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [18]:
tensor*10

tensor([10, 20, 30])

In [19]:
tensor-10

tensor([-9, -8, -7])

In [20]:
tensor/10

tensor([0.1000, 0.2000, 0.3000])

**Matrix Multiplication** most common operation
Rules for Matrix multiplications<br>
Both of this syntax work
`matmul`
`mm`

In [21]:
tensor1=torch.rand(2,2)
tensor2=torch.rand(2,2)

torch.matmul(tensor1,tensor2)

tensor([[1.0914, 0.9574],
        [1.2557, 1.1504]])

### How to solve Shape error
We can use transpose it switches axis and dimensions of tensor


In [22]:
tensor_A=torch.tensor([[1,2],
                       [2,3],
                       [4,5]])

tensor_B=torch.tensor([[7,8],
                       [9,10],
                       [11,12]])
torch.matmul(tensor_A,tensor_B)  #this error is solved after 2 cells

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [24]:
tensor_B.T

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [25]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 23,  29,  35],
        [ 38,  48,  58],
        [ 68,  86, 104]])

### Finding tensor aggregation
1. Min
2. Max
3. Mean
4. Sum

In [26]:
tensor=torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [27]:
print(f'min of tensor : {tensor.min()}')
print(f'max of tensor : {tensor.max()}')
print(f"mean of tensor : {tensor.type(torch.float32).mean()}")

min of tensor : 0
max of tensor : 90
mean of tensor : 45.0


positional min and mx

In [28]:
tensor.argmin(),tensor.argmax()

(tensor(0), tensor(9))

### Reshaping , Stacking ,Squeezing and squeegeeing

* Reshape - reshape tensor by our needs
* Stack - Stack the elements
* squeeze - remove all one direction removes one square-bracket
* unsqueeze - add one direction add one square bracket
* view - returns view of certain shape


In [29]:
tensor=torch.arange(0,100,10)

In [38]:
tensor_reshaped=tensor.reshape(2,5)
tensor_reshaped,tensor_reshaped.shape

(tensor([[ 0, 10, 20, 30, 40],
         [50, 60, 70, 80, 90]]),
 torch.Size([2, 5]))

## Selecting Data from tensor

### Indexing --similar to numpy

In [40]:
tensor[3]

tensor(30)

You can use `:` to  to get elemets

In [54]:
tensor[:3],tensor[:-4]

(tensor([ 0, 10, 20]), tensor([ 0, 10, 20, 30, 40, 50]))

## Pytorch and Numpy

`torch.from_numpy()` helps to convert array to tensor
<br>
`torch.Tensor.numpy()` helps to convert array from tensor

In [55]:
array=np.array([1,2,3])
tensor=torch.from_numpy(array)
tensor.shape,tensor

(torch.Size([3]), tensor([1, 2, 3]))

**Reproducibility** Helps in maintaining same element in randomness

In [2]:
import torch
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_A=torch.rand(2,2)

torch.manual_seed(RANDOM_SEED)
random_tensor_B=torch.rand(2, 2)

random_tensor_B,random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]),
 tensor([[0.8823, 0.9150],
         [0.3829, 0.9593]]),
 tensor([[True, True],
         [True, True]]))

## Acessing GPU

1. Check if GPU is available

In [3]:
!nvidia-smi

Tue Apr  8 10:27:44 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 572.83                 Driver Version: 572.83         CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4050 ...  WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   45C    P3             13W /   35W |       0MiB /   6141MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

2. Checking if cuda have acess to GPU

In [4]:
torch.cuda.is_available()

True

In [13]:
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [10]:
torch.cuda.device_count()

1

### Moving tensor to GPU (If available)

In [11]:
tensor=torch.rand(2,2)
tensor,tensor.device

(tensor([[0.9408, 0.1332],
         [0.9346, 0.5936]]),
 device(type='cpu'))

In [14]:
tensor=tensor.to(device)
tensor,tensor,device

(tensor([[0.9408, 0.1332],
         [0.9346, 0.5936]], device='cuda:0'),
 tensor([[0.9408, 0.1332],
         [0.9346, 0.5936]], device='cuda:0'),
 'cuda')